INSERT INTO public."Allergen" (name, description) VALUES 
('Gluten', 'Proteína presente en trigo, cebada y centeno'),
('Lactosa', 'Azúcar presente en la leche y productos lácteos'),
('Leche', 'Alergia a la proteína de la leche'),
('Huevo', 'Alergia a proteínas presentes en el huevo'),
('Maní', 'Alergia al cacahuate o maní'),
('Nueces de árbol', 'Incluye nuez, almendra, avellana, pistache, macadamia'),
('Almendras', 'Alergia específica a la almendra'),
('Avellanas', 'Alergia a avellanas'),
('Nueces', 'Alergia a nuez común'),
('Pistaches', 'Alergia a pistaches'),
('Anacardos', 'Alergia a anacardos o cashews'),
('Mariscos', 'Alergia a crustáceos como camarón, langosta, cangrejo'),
('Moluscos', 'Alergia a almejas, mejillones, ostiones'),
('Pescado', 'Alergia a pescado'),
('Soya', 'Alergia a soya'),
('Trigo', 'Alergia al trigo'),
('Sésamo', 'Alergia a semillas de sésamo'),
('Mostaza', 'Alergia a mostaza'),
('Apio', 'Alergia al apio'),
('Sulfitos', 'Sensibilidad o alergia a sulfitos usados como conservadores'),
('Maíz', 'Alergia al maíz'),
('Ajo', 'Alergia al ajo'),
('Cebolla', 'Alergia a la cebolla'),
('Tomate', 'Alergia al tomate'),
('Fresa', 'Alergia a la fresa'),
('Kiwi', 'Alergia al kiwi'),
('Plátano', 'Alergia al plátano'),
('Aguacate', 'Alergia al aguacate'),
('Chocolate', 'Alergia o sensibilidad al cacao'),
('Colorantes artificiales', 'Sensibilidad a colorantes alimentarios');